### ISSUE TITLE
Optimization Workshop?

### ISSUE THREAD

**Issue by kelle** [flatironinstitute/learn-sciware-dev#2]
There was some discussion at the March 28 meeting about a workshop usually held at Stony Brook that we may want to offer here. Could folks who know about that workshop please post some info in this issue? Thanks!

**Comment by Wentzell** [comment]
This Coding workshop is part of the [2019 Many Electron Collaboration Summer School](https://www.simonsfoundation.org/event/2019-many-electron-collaboration-summer-school/).
I had a quick chat with Emanuel Gull who is a co-organizer of this conference.
He says it is possible to sign up only for the Coding workshop.
Note however that it is targeted at first year graduate students with little background in coding and computational methods.

The workshop will take place from Friday June 7th until Sunday June 9th.
The exact agenda has not yet been posted but the [2018 agenda and collection of slides](https://www.simonsfoundation.org/event/2018-many-electron-collaboration-summer-school/)) should give you a good idea.

**Comment by dylex** [comment]
cleaning
