### ISSUE TITLE
I like it   (oh, and 10 passes not 9)

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/learn-sciware-dev#27]
I looked through the code examples, exercises, and slides, and think it's really cool.
Nice set of MCEs and well-structured exercises.

It will be fun for people to do live - esp if you give them time to actually think and type things themselves before you "give them the answer"^*   - and I think is about the right length (>60 mins to do including CI badge).
You can just tell them about codecov, and C++, if time, at the end.

* I know in last week's meeting there was discussion of format - how much to let people work on a problem, vs just having them copy what you type (as in carpentry).  I would suggest trying to let people think/type for 5 mins on each task, and resist telling them. Based on my experiences this *active learning* creates a lot more learning than copying...

**Comment by ahbarnett** [comment]
I forgot to say, I get 10 passes not 9, so you'll want to update slides. Have fun!

**Comment by ahbarnett** [comment]
PS is there a FI-wide reminder email going out today reminding people that this session is for everyone familiar w/ Python and teaches essential professional coding methods useful in any language...

**Comment by dylex** [comment]
thanks! i think all of this should be covered now.
